name: test
on:
  pull_request:
  push:
  schedule:
    - cron: '11 21 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - 13
          - 14
          - 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
